### ISSUE TITLE
Can't locate object method "end" via package "Thread::Queue

### ISSUE THREAD

**Issue by Triciasnow** [oushujun/EDTA#47]
Hello，
I used EDTA but I got an error when using the following script：

`perl /PARA/pp811/anaconda3/bin/EDTA/EDTA.pl -genome ref.fasta -cds CDS.fasta -anno 1 -evaluate 1 `

And then I got the following error output:

`Can't locate object method "end" via package "Thread::Queue" at /PARA/pp811/anaconda3/bin/EDTA/bin/LTR_FINDER_parallel/LTR_FINDER_parallel line 115, <List> line 1.
cat: ref.fasta.finder.combine.scn: No such file or directory
Can't locate object method "end" via package "Thread::Queue" at /PARA/pp811/anaconda3/bin/EDTA/bin/LTR_retriever/bin/LTR.identifier.pl line 125.
cp: cannot stat `ref.fasta.mod.retriever.scn.adj': No such file or directory
awk: cmd. line:1: fatal: cannot open file `ref.fasta.pass.list' for reading (No such file or directory)
Warning: LOC list - is empty.
Error: Error while loading sequencecp: cannot stat `ref.fasta.LTRlib.fa': No such file or directory
cp: cannot stat `VF36.GPM.fasta.LTRlib.fa': No such file or directory
Error: LTR results not found!

ERROR: Raw LTR results not found in ref.fasta.EDTA.raw/ref.fasta.LTR.raw.fa at /PARA/pp811/anaconda3/bin/EDTA/EDTA.pl line 284.`

Of all the results I've gotten so far, only LTR raw file，both TIR and Helitron raw fasta files are empty.
Any help or suggestion will be appreciated.
Thanks!

**Comment by oushujun** [comment]
Looks like your perl is not correctly installed. Please reinstall EDTA and
try again.

**Comment by oushujun** [comment]
This is identified as a potential bug when `/usr/bin/perl` is not correctly installed or restricted. The next update will resolve this issue.

**Comment by oushujun** [comment]
This issue should be resolved with the latest version (v1.7.4). Please update and test it again.

**Comment by Triciasnow** [comment]
Hello, I redownloaded version 1.7.4 through Github website, but it still appears as version 1.7.1 after installation, so I was wondering if the mirror source has been updated.

**Comment by oushujun** [comment]
Both the repo and the release package show the v1.7.4 version. Please double check. The easiest way to update is enter your EDTA directory then `git pull`

**Comment by Triciasnow** [comment]
I tried again. If I used conda to install it directly, it would be version 1.7.4，but if I use singularity this way it's still version 1.7.1

**Comment by oushujun** [comment]
Ahh, thank's for the heads up. We have not updated singularity yet and it may need some human interventions. Please use the conda version for the moment.

**Comment by oushujun** [comment]
Hello @Triciasnow,

Sorry for the delay. We just updated the Docker container to v1.7.7. Please update and try again.

Best,
Shujun
